### ISSUE TITLE
Verse Colour

### ISSUE THREAD

**Issue by ashleyman** [AntonyCorbett/OnlyV#29] opened 2019-05-11 00:14 UTC
We've noticed that when creating a custom theme the verse colour does not change to the colour you select on the picker. 

The default is yellow but we run a background image where yellow doesn't work. 

We have changed the main verse text colour to be white and done the same with the verse text but it remains yellow. 

We have tried to delete the custom theme and start again but it always stays yellow no matter what we do.

**Comment by AntonyCorbett** [comment] 2019-05-11 08:08
I can't reproduce this. There are 3 main elements to change - "Body Text", "Title Text" and "Verse Numbers". The default colour of the Verse Numbers and Title are yellow. The default colour of the Body Text is white. Are you sure you are setting the right elements?

**Comment by ashleyman** [comment] 2019-05-12 15:07
Yes.

On our Install we have all of those fields set to white and the verse colour still shows as yellow.

We’ve tried to create new themes and remove old and it still stays yellow. We have even tried to import themes created on different computers and when the themes are installed on the KH computer they always show yellow.

I didn’t have time today but I plan to re-install OnlyV and the theme creator as there must be a problem with the install if you can’t reproduce this.



Sent from iPhone.

On 11 May 2019, at 09:08, Antony Corbett <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce this. There are 3 main elements to change - "Body Text", "Title Text" and "Verse Numbers". The default colour of the Verse Numbers and Title are yellow. The default colour of the Body Text is white. Are you sure you are setting the right elements?

**Comment by AntonyCorbett** [comment] 2019-05-12 16:03
@ashleyman If the theme displays correctly on other PCs then I suspect that the monitor at the KH is not correctly calibrated for colour. The only other thing I can think of is that you are storing the theme in the wrong folder and OnlyV is using one of the same name that is tired in the correct folder. You can test for this latter possibility by changing one of the other properties of the theme, e.g. background, and checking that this is picked up on OnlyV.

**Comment by AntonyCorbett** [comment] 2019-07-26 16:13
@ashleyman closing for now. Please let me know if this still remains an issue after testing as I suggested above. Thanks. Antony

**Closed by AntonyCorbett** 2019-07-26 16:13 UTC
Labels: question
