### ISSUE TITLE
Unable to save images

### ISSUE THREAD

**Issue by jsquiggz** [AntonyCorbett/OnlyV#16] opened 2019-01-06 20:06 UTC
I am unable to save images, the program says it has saved the image then gives an error message as per the attached screenshots

![2019-01-06 1](https://user-images.githubusercontent.com/41520698/50740942-7be4ed80-11ee-11e9-8d4c-6af45a7ed771.png)
![2019-01-06](https://user-images.githubusercontent.com/41520698/50740945-83a49200-11ee-11e9-9364-a33511125f97.png)

**Comment by AntonyCorbett** [comment] 2019-01-06 22:03
@jsquiggz Please send the log file

**Comment by jsquiggz** [comment] 2019-01-06 22:07
Where is the log file?

**Comment by jsquiggz** [comment] 2019-01-06 22:09
[log-20190106.txt](https://github.com/AntonyCorbett/OnlyV/files/2730916/log-20190106.txt)

**Comment by AntonyCorbett** [comment] 2019-01-06 22:49
@jsquiggz what is the image folder set to? What version are you using?

**Comment by jsquiggz** [comment] 2019-01-07 07:04
Have tried different Image folder locations inc directly to the desktop and
another folder on the C: drive.

I am using the latest version which I downloaded yesterday.

**Comment by AntonyCorbett** [comment] 2019-01-07 07:48
@jsquiggz thnaks. Please would you try the latest release (v1.2.0.5) which contains improved logging. The issue is likely to remain but at least we'll get a more informative log.

**Comment by jsquiggz** [comment] 2019-01-07 14:46
[log-20190107.txt](https://github.com/AntonyCorbett/OnlyV/files/2733124/log-20190107.txt)
I have downloaded the new version, and still get the error message. I have included the log file.

**Comment by jsquiggz** [comment] 2019-01-07 17:33
Thanks. Strange it was working before and I have admin rights on the
account. Can you advise a quick fix?

**Comment by AntonyCorbett** [comment] 2019-01-07 17:57
I assume you are logged on as user "Lorraine". Check permissions by opening the folder (C:\Users\Lorraine\Documents\OnlyV\BibleTextImages) in Windows Explorer and attempting to create a file. What do you find?

**Comment by jsquiggz** [comment] 2019-01-07 18:09
It allows me to create a file and a folder

**Comment by AntonyCorbett** [comment] 2019-01-07 18:15
ok. Are you running OnlyV as another user?

**Comment by AntonyCorbett** [comment] 2019-01-07 18:47
Glad you're sorted. It could be several other things, e.g. an existing file with read-only attribute. But it sounds like we can close this issue now

**Closed** 2019-01-08 15:15 UTC
Labels: question
